### ISSUE TITLE
Project name change to `Schedulify` and add contribution docs. 

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [GDSCASECBE/appointmentScheduler#4]
## Description

The existing repository name is too long and not very catchy. A name change would be a small upgrade for the project.

Also, was thinking about adding the following to standardize things in this repository :

[ ] Add - `CONTRIBUTION.md`
[ ] Add - `PULL_REQUEST_TEMPLATE.md`
[ ] Add - `ISSUES_TEMPLATE.md`

### Reviewer
@pranavsuriya-sr , shall we implement the above mentioned ideas ?

**Comment by pranavsuriya-sr** [comment]
Fine go on. Assigning you this issue.

**Comment by pranavsuriya-sr** [comment]
Good job
